# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spec_help_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpecHelpWindow(object):
    def setupUi(self, SpecHelpWindow):
        SpecHelpWindow.setObjectName("SpecHelpWindow")
        SpecHelpWindow.resize(717, 558)
        self.centralwidget = QtWidgets.QWidget(SpecHelpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.info_content = QtWidgets.QLabel(self.centralwidget)
        self.info_content.setGeometry(QtCore.QRect(70, 70, 591, 231))
        self.info_content.setAutoFillBackground(False)
        self.info_content.setStyleSheet("color:white;\n"
"padding:10px;\n"
"background-color:gray;\n"
"border-radius:10px;\n"
"")
        self.info_content.setTextFormat(QtCore.Qt.AutoText)
        self.info_content.setScaledContents(False)
        self.info_content.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.info_content.setWordWrap(True)
        self.info_content.setObjectName("info_content")
        self.spec_image = QtWidgets.QLabel(self.centralwidget)
        self.spec_image.setGeometry(QtCore.QRect(190, 320, 331, 201))
        self.spec_image.setStyleSheet("border-radius:10px;")
        self.spec_image.setScaledContents(True)
        self.spec_image.setObjectName("spec_image")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(70, 0, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        SpecHelpWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SpecHelpWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 22))
        self.menubar.setObjectName("menubar")
        SpecHelpWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SpecHelpWindow)
        self.statusbar.setObjectName("statusbar")
        SpecHelpWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SpecHelpWindow)
        QtCore.QMetaObject.connectSlotsByName(SpecHelpWindow)

    def retranslateUi(self, SpecHelpWindow):
        _translate = QtCore.QCoreApplication.translate
        SpecHelpWindow.setWindowTitle(_translate("SpecHelpWindow", "Spectrogram Help Window"))
        self.info_content.setText(_translate("SpecHelpWindow", "Explanation text"))
        self.spec_image.setText(_translate("SpecHelpWindow", "Image"))
        self.title_label.setText(_translate("SpecHelpWindow", "CheatSheet Window"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpecHelpWindow = QtWidgets.QMainWindow()
    ui = Ui_SpecHelpWindow()
    ui.setupUi(SpecHelpWindow)
    SpecHelpWindow.show()
    sys.exit(app.exec_())
