# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rt_sine_help_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RTSineHelpWindow(object):
    def setupUi(self, RTSineHelpWindow):
        RTSineHelpWindow.setObjectName("RTSineHelpWindow")
        RTSineHelpWindow.resize(880, 573)
        RTSineHelpWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(RTSineHelpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 861, 521))
        self.scrollArea.setStyleSheet("QScrollBar{\n"
"    border:none;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: gray;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: #0096ff;\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(28, 113, 216);\n"
"\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(28, 113, 216);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:gray;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: black;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: black;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: gray;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: black;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: black;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 845, 888))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 870))
        self.frame.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 460, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 510, 791, 331))
        self.label_2.setStyleSheet("background-color:white;\n"
"padding:10px;\n"
"border-radius:10px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets/spectrum_help.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 801, 361))
        self.label_3.setStyleSheet("background-color:white;\n"
"padding:2px;\n"
"border-radius:10px;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("assets/help_rt_sine_transformations.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        RTSineHelpWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RTSineHelpWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 22))
        self.menubar.setObjectName("menubar")
        RTSineHelpWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RTSineHelpWindow)
        self.statusbar.setObjectName("statusbar")
        RTSineHelpWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RTSineHelpWindow)
        QtCore.QMetaObject.connectSlotsByName(RTSineHelpWindow)

    def retranslateUi(self, RTSineHelpWindow):
        _translate = QtCore.QCoreApplication.translate
        RTSineHelpWindow.setWindowTitle(_translate("RTSineHelpWindow", "Help Window"))
        self.label.setText(_translate("RTSineHelpWindow", "What is a Spectrum?"))
        self.label_4.setText(_translate("RTSineHelpWindow", "How does this work?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RTSineHelpWindow = QtWidgets.QMainWindow()
    ui = Ui_RTSineHelpWindow()
    ui.setupUi(RTSineHelpWindow)
    RTSineHelpWindow.show()
    sys.exit(app.exec_())
